### PR TITLE
Please check out my code

### PR DESCRIPTION
**Pull request by AntonM711**

### CODE REVIEW

**Comment by AntonM711** [comment]
wtf it says i have a conflict

**Comment by yanaf02** [comment]
conflict is here

**Comment by yanaf02** [comment]
i know dude

**Comment by AntonM711** [comment]
ah i figured..we all try to add a file with same name. Roza added hers first now the rest have conflict

**Comment by yanaf02** [comment]
yep lets see

**Comment by yanaf02** [comment]
goddammit

**Comment by AntonM711** [comment]
i changed name of the class, can you check it?

**Review by yanaf02 — APPROVED** [review]
code works fine

**Comment by yanaf02** [comment]
should be working now

**Pull request merged**
